export const Data = [
  {
    id: "9b31aba0-3798-454b-abd3-035c37c7e336",
    name: "Topic Test",
    question:
      "<p>Three numbers are in the ratio 5: 7: 9 and their L.C.M is 6300. Their H.C.F is</p>",
    type: "SINGLE_SELECT",
    description: null,
    imgURL: null,
    questionBankId: null,
    testQuestionsSetId: null,
    orderNo: 1,
    currentQuestionNo: null,
    totalBundle: null,
    conceptName: "Arithmetic",
    status: null,
    testSectionId: null,
    topicId: "2b5fbc19-3dbd-4170-8f78-9e4e153bd7ca",
    resetTime: true,
    testExecutionId: null,
    totalNoOfQuestion: 7,
    remainingTime: null,
    testTitle: null,
    testType: null,
    questions: null,
    isBookmarked: null,
    isHaveDescription: false,
    isHaveImage: false,
    expectedTime: null,
    score: null,
    isCalculator: false,
    topText:
      "Select one entry for the blank. Fill the blank in the way that best completes the text.",
    bottomText: "Select one answer choice.",
    noOfAnswer: 1,
    testSectionName: null,
    currentTestSection: null,
    totalNoOfTestSection: null,
    answerHint: null,
    totalNoOfQuestionSection: null,
    noOfAttempt: null,
    choices: [
      {
        id: "dc662983-84d3-4924-8792-8cc239fa58e2",
        type: "TEXT",
        text: "10",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 1,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "be538bb4-3e3c-4d03-87b2-0f9a0b2094d2",
        type: "TEXT",
        text: "20",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 2,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "6517252b-5d5e-4be1-8fb9-856500b78c9a",
        type: "TEXT",
        text: "30",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 3,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "f5d8c915-b58e-4bf8-aa4a-40c467774b17",
        type: "TEXT",
        text: "40",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 4,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
    ],
  },
  {
    id: "819d4315-2f9f-4094-93f7-7f3864e678cf",
    name: "Topic Test",
    question:
      "<p>The least multiple of 8, which leaves remainder of 4, when divided by 3 , 9, 12 and 15 is:</p>",
    type: "SINGLE_SELECT",
    description: null,
    imgURL: null,
    questionBankId: null,
    testQuestionsSetId: null,
    orderNo: 2,
    currentQuestionNo: null,
    totalBundle: null,
    conceptName: "Arithmetic",
    status: null,
    testSectionId: null,
    topicId: "2b5fbc19-3dbd-4170-8f78-9e4e153bd7ca",
    resetTime: false,
    testExecutionId: null,
    totalNoOfQuestion: 7,
    remainingTime: null,
    testTitle: null,
    testType: null,
    questions: null,
    isBookmarked: null,
    isHaveDescription: false,
    isHaveImage: false,
    expectedTime: null,
    score: null,
    isCalculator: false,
    topText:
      "Select one entry for the blank. Fill the blank in the way that best completes the text.",
    bottomText: "Select one answer choice.",
    noOfAnswer: 1,
    testSectionName: null,
    currentTestSection: null,
    totalNoOfTestSection: null,
    answerHint: null,
    totalNoOfQuestionSection: null,
    noOfAttempt: null,
    choices: [
      {
        id: "64ecfec5-3a58-4444-828d-6d5bc8d69edd",
        type: "TEXT",
        text: "96",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 1,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "ddfb15ea-db40-4c7c-9495-c633bcdb9fe1",
        type: "TEXT",
        text: "184",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 2,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "e0cc09b8-d99e-4e7c-a742-fa47ac8f5dda",
        type: "TEXT",
        text: "368",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 3,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "85630664-1719-4dec-81e0-c0cffcb546e8",
        type: "TEXT",
        text: "736",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 4,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
    ],
  },
  {
    id: "133c822d-fea6-4b9a-aeb7-d3371103fda5",
    name: "Single image choice",
    question:
      "<p>There are 2 numbers such that x>y, H.C.Fx,y=h and L.C.Mx,y=l. What is the LCM of (x – y) and y?</p>",
    type: "SINGLE_SELECT",
    description: null,
    imgURL: null,
    questionBankId: null,
    testQuestionsSetId: null,
    orderNo: 3,
    currentQuestionNo: null,
    totalBundle: null,
    conceptName: "Arithmetic",
    status: null,
    testSectionId: null,
    topicId: "2b5fbc19-3dbd-4170-8f78-9e4e153bd7ca",
    resetTime: false,
    testExecutionId: null,
    totalNoOfQuestion: 7,
    remainingTime: null,
    testTitle: null,
    testType: null,
    questions: null,
    isBookmarked: null,
    isHaveDescription: false,
    isHaveImage: false,
    expectedTime: null,
    score: null,
    isCalculator: false,
    topText:
      "Select one entry for the blank. Fill the blank in the way that best completes the text.",
    bottomText: "Select one answer choice.",
    noOfAnswer: 1,
    testSectionName: null,
    currentTestSection: null,
    totalNoOfTestSection: null,
    answerHint: null,
    totalNoOfQuestionSection: null,
    noOfAttempt: null,
    choices: [
      {
        id: "42f9d8e1-3fb3-4e37-81b2-c0e3a85a1f9d",
        type: "IMAGE",
        text: null,
        choiceImage: "https://i.im.ge/2022/01/04/XuBSwc.png",
        mappedCourses: [],
        bundleNo: null,
        orderNo: 1,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "dee5b832-bcab-4842-bcdc-7f488c60d2dc",
        type: "IMAGE",
        text: null,
        choiceImage: "https://i.im.ge/2022/01/04/XuBdKL.png",
        mappedCourses: [],
        bundleNo: null,
        orderNo: 2,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "4fff1aab-0ef7-4ed1-9a64-739a02c71117",
        type: "IMAGE",
        text: null,
        choiceImage: "https://i.im.ge/2022/01/04/XuBsXG.png",
        mappedCourses: [],
        bundleNo: null,
        orderNo: 3,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "72aa721e-fcc0-452d-af42-0954e25a84c6",
        type: "IMAGE",
        text: null,
        choiceImage: "https://i.im.ge/2022/01/04/XuBaix.png",
        mappedCourses: [],
        bundleNo: null,
        orderNo: 4,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
    ],
  },
  {
    id: "3a55b147-6b4f-479a-ba17-d79b3aa6fadf",
    name: "Passage Question",
    question:
      "<p>6 different sarees varieties of count 32, 216, 136, 88, 184,120 were ordered for Mr. Bean wedding. The sarees need to be packed in such a way that each box has the same variety of saree and the number of sarees in each box is also same.</p>",
    type: "SINGLE_SELECT",
    description: "<p>Find the minimum number of boxes required to pack?</p>",
    imgURL: null,
    questionBankId: null,
    testQuestionsSetId: null,
    orderNo: 4,
    currentQuestionNo: null,
    totalBundle: null,
    conceptName: "Arithmetic",
    status: null,
    testSectionId: null,
    topicId: "2b5fbc19-3dbd-4170-8f78-9e4e153bd7ca",
    resetTime: false,
    testExecutionId: null,
    totalNoOfQuestion: 7,
    remainingTime: null,
    testTitle: null,
    testType: null,
    questions: null,
    isBookmarked: null,
    isHaveDescription: true,
    isHaveImage: false,
    expectedTime: null,
    score: null,
    isCalculator: false,
    topText: null,
    bottomText: "Select one answer choice.",
    noOfAnswer: 1,
    testSectionName: null,
    currentTestSection: null,
    totalNoOfTestSection: null,
    answerHint: null,
    totalNoOfQuestionSection: null,
    noOfAttempt: null,
    choices: [
      {
        id: "61b94455-94ab-4975-847d-00ac473e47ce",
        type: "TEXT",
        text: "128",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 1,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "a78b2225-dcf4-4cbf-8bd9-74e3f79d95ab",
        type: "TEXT",
        text: "79",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 2,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "db431c3d-d9d5-409c-9aea-faae2c4dc960",
        type: "TEXT",
        text: "69",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 3,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "ced86477-6e38-4235-aa46-7195b7b4ddc7",
        type: "TEXT",
        text: "97",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 4,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
    ],
  },
  {
    id: "85743fee-d96b-4145-923b-3026687c59d1",
    name: "Multi choice question",
    question:
      "<p>How many pairs of positive integers ‘p’, ‘q’ exist such that HCF of ‘p,q’ = 35 and sum ‘p’ and ‘q’ = 1085? in decimals</p>",
    type: "MULTI_CHOICE",
    description: null,
    imgURL: null,
    questionBankId: null,
    testQuestionsSetId: null,
    orderNo: 5,
    currentQuestionNo: null,
    totalBundle: null,
    conceptName: "Arithmetic",
    status: null,
    testSectionId: null,
    topicId: "2b5fbc19-3dbd-4170-8f78-9e4e153bd7ca",
    resetTime: false,
    testExecutionId: null,
    totalNoOfQuestion: 7,
    remainingTime: null,
    testTitle: null,
    testType: null,
    questions: null,
    isBookmarked: null,
    isHaveDescription: false,
    isHaveImage: false,
    expectedTime: null,
    score: null,
    isCalculator: false,
    topText:
      "Select the three answer choices that, when used to complete the sentence, fit the meaning of the sentence as a whole and produce completed sentences that are alike in meaning.",
    bottomText: "Select three answer choices.",
    noOfAnswer: 3,
    testSectionName: null,
    currentTestSection: null,
    totalNoOfTestSection: null,
    answerHint: null,
    totalNoOfQuestionSection: null,
    noOfAttempt: null,
    choices: [
      {
        id: "4413d829-78b6-4326-b539-6ab7406ea181",
        type: "TEXT",
        text: "5",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 1,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "40e706dc-08b2-449b-8305-119e78831ada",
        type: "TEXT",
        text: "10",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 2,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "c371f815-a07d-49cc-a70a-ec142994ee35",
        type: "TEXT",
        text: "12",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 3,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "a44b85ad-a8a7-4671-a8fe-b529aee7706a",
        type: "TEXT",
        text: "15",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 4,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "1c4e57d2-16be-486c-8cb0-c3f738b86a34",
        type: "TEXT",
        text: "20",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 5,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "3732055c-eec6-4e54-ab00-c8bb376c5632",
        type: "TEXT",
        text: "27",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 6,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "c296e83d-7434-447e-92e4-8ea5dfd970ad",
        type: "TEXT",
        text: "29",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 7,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "5bd64a86-1628-4223-a0fc-03cffff7521c",
        type: "TEXT",
        text: "31",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: null,
        orderNo: 8,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
    ],
  },
  {
    id: "7b550187-bb50-4bc3-857f-3e80bd34d60f",
    name: "Subjective question",
    question:
      "<p>The sum of two non-co-prime numbers added to their HCF gives us 91. How many such pairs are possible?</p>",
    type: "SUBJECTIVE",
    description: null,
    imgURL: "https://i.im.ge/2022/01/04/XuB9KK.png",
    questionBankId: null,
    testQuestionsSetId: null,
    orderNo: 6,
    currentQuestionNo: null,
    totalBundle: null,
    conceptName: "Arithmetic",
    status: null,
    testSectionId: null,
    topicId: "2b5fbc19-3dbd-4170-8f78-9e4e153bd7ca",
    resetTime: false,
    testExecutionId: null,
    totalNoOfQuestion: 7,
    remainingTime: null,
    testTitle: null,
    testType: null,
    questions: null,
    isBookmarked: null,
    isHaveDescription: false,
    isHaveImage: true,
    expectedTime: null,
    score: null,
    isCalculator: false,
    topText: null,
    bottomText: null,
    noOfAnswer: 1,
    testSectionName: null,
    currentTestSection: null,
    totalNoOfTestSection: null,
    answerHint: null,
    totalNoOfQuestionSection: null,
    noOfAttempt: null,
    choices: [],
  },
  {
    id: "c94f3cf6-da32-4b7d-8be8-148901f796cc",
    name: "Bundle question",
    question:
      "<p>Six alarm bells commence ringing together and ring at intervals of 2, 4,6, 8, 10 and 12 seconds respectively. In 60 minutes, how many times do they ring together?</p>",
    type: "BUNDLE",
    description: null,
    imgURL: null,
    questionBankId: null,
    testQuestionsSetId: null,
    orderNo: 7,
    currentQuestionNo: null,
    totalBundle: 3,
    conceptName: "Arithmetic",
    status: null,
    testSectionId: null,
    topicId: "2b5fbc19-3dbd-4170-8f78-9e4e153bd7ca",
    resetTime: false,
    testExecutionId: null,
    totalNoOfQuestion: 7,
    remainingTime: null,
    testTitle: null,
    testType: null,
    questions: null,
    isBookmarked: null,
    isHaveDescription: false,
    isHaveImage: false,
    expectedTime: null,
    score: null,
    isCalculator: false,
    topText:
      "For each blank select one entry from the corresponding column of choice.  Fill all blanks in the way but best completes the text.",
    bottomText: "Select one entry from each column.",
    noOfAnswer: 3,
    testSectionName: null,
    currentTestSection: null,
    totalNoOfTestSection: null,
    answerHint: null,
    totalNoOfQuestionSection: null,
    noOfAttempt: null,
    choices: [
      {
        id: "3cbd65ed-7d64-4b4b-ba8d-70f6e16f22dc",
        type: "TEXT",
        text: "21 times",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: 2,
        orderNo: 1,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "845df313-70fb-4088-9fa1-5a1b32da105b",
        type: "TEXT",
        text: "31 times",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: 1,
        orderNo: 1,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "063e9305-e63e-47e4-b8a9-08ef4eb96c4e",
        type: "TEXT",
        text: "16 times",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: 3,
        orderNo: 1,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "28b4e35b-5b0e-436d-8845-60802ffcfc26",
        type: "TEXT",
        text: "20 times",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: 2,
        orderNo: 2,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "ebb68bcc-122d-47c0-8790-8876f7a162d7",
        type: "TEXT",
        text: "11 times",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: 1,
        orderNo: 2,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "ec7768fa-4863-4dba-85c3-a376918ab640",
        type: "TEXT",
        text: "15 times",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: 3,
        orderNo: 2,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "f0d8c18d-117f-462a-878e-39640d579292",
        type: "TEXT",
        text: "10 times",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: 1,
        orderNo: 3,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "316daabd-73eb-443e-aa59-d41dcf2fa0b1",
        type: "TEXT",
        text: "14 times",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: 3,
        orderNo: 3,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
      {
        id: "5ab8cbe3-c530-43f3-8d91-d7796d73393f",
        type: "TEXT",
        text: "19 times",
        choiceImage: null,
        mappedCourses: [],
        bundleNo: 2,
        orderNo: 3,
        createdAt: null,
        updatedAt: null,
        imageUrl: null,
        imageType: null,
        correctChoice: null,
      },
    ],
  },
];
