export const tableContent = [
  {
    id: 1,
    topicName: "Probability",
    startDate: "12/3/22",
    endDate: "12/12/22",
    test: "Test1",
    queAttempt: "21/32",
    duration: "20min",
    score: "19/32",
    status: "completed",
    icon: "complete",
  },

  {
    id: 2,
    topicName: "Ratio",
    startDate: "-",
    endDate: "-",
    test: "Test1",
    queAttempt: "-",
    duration: "-",
    score: "-",
    status: "Yet to start",
    icon: "yettostart",
  },

  {
    id: 3,
    topicName: "Ratio & Algebra",
    startDate: "20/3/22",
    endDate: "12/6/22",
    test: "Test3",
    queAttempt: "-",
    duration: "-",
    score: "-",
    status: "On Going",
    icon: "ongoing",
  },
];
