let data = {
  content: [
    {
      name: 'Classification of Numbers',
      testType: 'QUESTIONBANK',
      courseName: 'GMAT',
      topicName: 'Classification of Numbers',
      status: 'Live',
      queAssigns: null,
      queFilled: null,
    },
    {
      name: 'Classification of Numbers',
      testType: 'QUESTIONBANK',
      courseName: 'GRE',
      topicName: 'Classification of Numbers',
      status: 'Live',
      queAssigns: null,
      queFilled: null,
    },
    {
      name: 'Classification of Numbers Test 1',
      testType: 'TOPIC',
      courseName: 'GMAT',
      topicName: 'Classification of Numbers',
      status: 'Live',
      queAssigns: 2,
      queFilled: 2,
    },
    {
      name: 'Classification of Numbers Test 1',
      testType: 'TOPIC',
      courseName: 'GRE',
      topicName: 'Classification of Numbers',
      status: 'Live',
      queAssigns: 2,
      queFilled: 2,
    },
    {
      name: 'Descriptive Statistics',
      testType: 'QUESTIONBANK',
      courseName: 'GMAT',
      topicName: 'Descriptive Statistics',
      status: 'Live',
      queAssigns: null,
      queFilled: null,
    },
    {
      name: 'Descriptive Statistics Test 1',
      testType: 'TOPIC',
      courseName: 'GMAT',
      topicName: 'Descriptive Statistics',
      status: 'Live',
      queAssigns: 2,
      queFilled: 2,
    },
    {
      name: 'Evaluate the Argument',
      testType: 'QUESTIONBANK',
      courseName: 'GRE',
      topicName: 'Evaluate the Argument',
      status: 'Live',
      queAssigns: null,
      queFilled: null,
    },
    {
      name: 'Evaluate the Argument Test 1',
      testType: 'TOPIC',
      courseName: 'GRE',
      topicName: 'Evaluate the Argument',
      status: 'Live',
      queAssigns: 2,
      queFilled: 2,
    },
    {
      name: 'Find the Assumption',
      testType: 'QUESTIONBANK',
      courseName: 'GMAT',
      topicName: 'Find the Assumption',
      status: 'Live',
      queAssigns: null,
      queFilled: null,
    },
    {
      name: 'Find the Assumption Test 1',
      testType: 'TOPIC',
      courseName: 'GMAT',
      topicName: 'Find the Assumption',
      status: 'Live',
      queAssigns: 2,
      queFilled: 2,
    },
  ],
  totalElements: 42,
  totalPages: 5,
};

export default data;
